import {Out} from '@snickbit/out'
import {safeVarName, slugify} from '@snickbit/utilities'
import path from 'path'

export const DEFAULT_CONFIG_NAME = 'indexer.config.json'

export const posix = path.posix

export const FILE_PATTERN = '*.+(js|mjs|vue|ts)'

export const indexPredicate = p => !p.match(/\/index\.[a-z]+$/)

export const indexer_banner = '// WARNING: This file is automatically generated. Any changes will be lost the next time the generator is run.'

export const $out = new Out('indexer')

export function getExportName(fp) {
	const dirname = path.dirname(fp)
	const basename = path.basename(fp)
	const filename = path.basename(fp, path.extname(fp))
	const export_name = safeVarName(filename)
	const slug = safeVarName(slugify(path.join(dirname, filename)))
	return {
		basename,
		filename,
		export_name,
		slug
	}
}
